# Email address to use in the 'from' field for emails sent by Kochiku.
sender_email_address: 'kochiku@icisapp.com'

# Email address where kochiku should send problems with the build system (for example, errors),
# as distinct from failures in a particular test (which go to the people who committed code).
kochiku_notifications_email_address: 'kochiku-notifications@icisapp.com'

# Domain name to use in constructing generic addresses. For example noreply@example.com in git commits.
domain_name: 'icisapp.com'

# Set to true if Kochiku is served over https
use_https: true

# Host name where Kochiku is serving web pages.
kochiku_host: 'kochiku.icisapp.com'

# If you commit with hitch/git-pair, etc, set this in order to send email to each person in the pair.
# For example, github+joe+bob@example.com will turn into emails to joe@example.com and bob@example.com
# if git_pair_email_prefix is set to 'github'.
git_pair_email_prefix: 'github'

# Mail server which will accept mail on port 25 (standard SMTP port). If you need to use another port,
# or other settings, you currently need to edit the kochiku source (config.action_mailer settings in
# config/environments/production.rb).
smtp_server: 'localhost'

# Host and port to connect to for Redis communication.
redis_host: '127.0.0.1'
redis_port: 6379

# List your git servers
git_servers:
  github.com:
    type: github
    oauth_token_file: /app/kochiku/secrets/kochiku-github-oauth
